truncate table employee ;
truncate table degree ;
truncate table team ;
truncate table OPRATIONS;
truncate table injured ;
truncate table department;
truncate table room ;
delete from employee ;
delete from degree ;
delete from team ;
delete from OPRATIONS;
delete from injured ;
delete from department;
delete from room ;